language: android
android:
  components:
    - build-tools-23.0.2
    - android-23
    - sys-img-x86-android-tv-l
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
# script:
#  - ./gradlew build
after_success:
  # Upload .apk file to deploygate
  - curl -F "file=@build/apk/${APP_NAME}.apk" -F "token=${DEPLOYGATE_API_KEY}" https://deploygate.com/api/users/${DEPLOYGATE_USER_NAME}/apps
branches:
  only:
    - change_for_ci
